### ISSUE TITLE
Register Doctrine filter automatically (e.g. via CompilerPass)

### ISSUE THREAD

**Issue by janopae** [webfactory/webfactory-visibility-filter-bundle#4]
Zum Punkt

The filter class needs to be registered manually.

```yaml
# src/config.yml
doctrine:
    orm:
        filters:
            visibility: Webfactory\VisibilityFilterBundle\Filter\StrategyConsideringSQLFilter
```

Aus der README:

Muss man das im Projekt schreiben? Geht das nicht über z.B. einen CompilerPass (idk!)? Falls man die Config wirklich braucht, sollte sie dann nicht im Bundle leben und man hier nur die Bundle-Config einbinden müssen? Dann müsste man z.B. auch nicht auf den Namen Acht geben/den erklären?
